import type { Metadata } from "next";
import { Manrope } from "next/font/google";

import "./globals.css";

import { cn } from "@/lib/utils";
import Provider from "@/components/ui/provider";

const font = Manrope({ 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Website pemilu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(font.className)}>
      <Provider>
        {children}
      </Provider>
      </body>
    </html>
  );
}
